In [10]:
import pandas as pd

file_path = '/Users/tarunt/Downloads/customer_shopping_behavior.csv'
df = pd.read_csv(file_path)
print(f'Successfully loaded {len(df)} rows and {len(df.columns)} columns from {file_path}')
print(df.head())

Successfully loaded 3900 rows and 18 columns from /Users/tarunt/Downloads/customer_shopping_behavior.csv
   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [12]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [13]:
print('Missing values in each column:')
print(df.isnull().sum())

Missing values in each column:
Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
print("Missing values in 'Review Rating' after imputation:")
print(df['Review Rating'].isnull().sum())

Missing values in 'Review Rating' after imputation:
0

In [15]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]
print("Updated column names:")
print(df.columns)

Updated column names:
Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [16]:
bins = [0, 29, 49, 64, df['age'].max()]
labels = ['young adult', 'adult', 'middle aged', 'senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

print("Value counts for the new 'age_group' column:")
print(df['age_group'].value_counts())
print("\nFirst 5 rows with the new 'age_group' column:")
print(df[['age', 'age_group']].head(20))

Value counts for the new 'age_group' column:
age_group
adult          1463
middle aged    1132
young adult     878
senior          427
Name: count, dtype: int64

First 5 rows with the new 'age_group' column:
    age    age_group
0    55  middle aged
1    19  young adult
2    50  middle aged
3    21  young adult
4    45        adult
5    46        adult
6    63  middle aged
7    27  young adult
8    26  young adult
9    57  middle aged
10   53  middle aged
11   30        adult
12   61  middle aged
13   65       senior
14   64  middle aged
15   64  middle aged
16   25  young adult
17   53  middle aged
18   52  middle aged
19   66       senior

In [17]:
frequency_mapping = {
    'Daily': 1,
    'Weekly': 7,
    'Fortnightly': 14,
    'Bi-Weekly': 14,
    'Monthly': 30,  # Assuming a standard month for 'Monthly'
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Annually': 365
}

# Ensure all unique values in 'frequency_of_purchases' are in the mapping
# If there are any not in the mapping, they will result in NaN
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

print("Value counts for the new 'purchase_frequency_days' column:")
print(df['purchase_frequency_days'].value_counts())
print("\nFirst 5 rows with 'frequency_of_purchases' and 'purchase_frequency_days' columns:")
print(df[['frequency_of_purchases', 'purchase_frequency_days']].head())

Value counts for the new 'purchase_frequency_days' column:
purchase_frequency_days
90     1147
14     1089
365     572
30      553
7       539
Name: count, dtype: int64

First 5 rows with 'frequency_of_purchases' and 'purchase_frequency_days' columns:
  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365

In [18]:
print("Unique values for 'discount_applied':", df['discount_applied'].unique())
print("Unique values for 'promo_code_used':", df['promo_code_used'].unique())

print("\nCross-tabulation of 'discount_applied' and 'promo_code_used':")
contingency_table = pd.crosstab(df['discount_applied'], df['promo_code_used'])
print(contingency_table)

# Further analysis: Check if 'Promo Code Used' always implies 'Discount Applied'
# If 'Yes' in 'promo_code_used' always corresponds to 'Yes' in 'discount_applied'
# And if 'No' in 'promo_code_used' always corresponds to 'No' in 'discount_applied' (or vice-versa), then they are redundant

is_redundant = False
if 'Yes' in contingency_table.columns and 'No' in contingency_table.columns:
    # Check if 'Yes' in 'promo_code_used' always leads to 'Yes' in 'discount_applied'
    if contingency_table.loc['No', 'Yes'] == 0:
        # Check if 'No' in 'promo_code_used' always leads to 'No' in 'discount_applied'
        if contingency_table.loc['Yes', 'No'] == 0:
            is_redundant = True

if is_redundant:
    print("\nBased on the cross-tabulation, 'discount_applied' and 'promo_code_used' appear to be redundant, as 'Yes' in one consistently corresponds to 'Yes' in the other (and 'No' to 'No').")
else:
    print("\nBased on the cross-tabulation, 'discount_applied' and 'promo_code_used' do not appear to be perfectly redundant. There are cases where one is 'Yes' and the other is 'No'.")

Unique values for 'discount_applied': <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Unique values for 'promo_code_used': <StringArray>
['Yes', 'No']
Length: 2, dtype: str

Cross-tabulation of 'discount_applied' and 'promo_code_used':
promo_code_used     No   Yes
discount_applied
No                2223     0
Yes                  0  1677

Based on the cross-tabulation, 'discount_applied' and 'promo_code_used' appear to be redundant, as 'Yes' in one consistently corresponds to 'Yes' in the other (and 'No' to 'No').

In [19]:
df.drop('promo_code_used', axis=1, inplace=True)
print("Column 'promo_code_used' dropped successfully.")
print("Updated columns:", df.columns)

Column 'promo_code_used' dropped successfully.
Updated columns: Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [20]:
%pip install sqlalchemy pymysql pandas

Requirement already satisfied: sqlalchemy in ./tarun final/.venv/lib/python3.13/site-packages (2.0.48)
Requirement already satisfied: pymysql in ./tarun final/.venv/lib/python3.13/site-packages (1.1.2)
Requirement already satisfied: pandas in ./tarun final/.venv/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: typing-extensions>=4.6.0 in ./tarun final/.venv/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in ./tarun final/.venv/lib/python3.13/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./tarun final/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./tarun final/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [21]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "builder!12"
host = "localhost"
port = "3306"
database = "customer_behavior"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,adult,365